<?php
if (session_status() === PHP_SESSION_NONE) session_start();
$role = $_SESSION['user']['role'] ?? '';
$name = $_SESSION['user']['name'] ?? 'Pengguna';
$page = basename($_SERVER['PHP_SELF']);
function navActive($files){ global $page; return in_array($page,(array)$files,true)?'active':''; }
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title><?=htmlspecialchars($page==='index.php'?'Dashboard':'RestoPOS • '.ucfirst(pathinfo($page,PATHINFO_FILENAME)))?></title>
<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🍽️</text></svg>">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"></script>
<style>
:root{--primary:#2563eb;--indigo:#4f46e5;--ink:#172033;--muted:#7b879d;--bg:#f5f7fb;--line:#e8edf5}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Poppins,sans-serif;font-size:13px}.sidebar{position:fixed;inset:0 auto 0 0;width:250px;background:#111827;color:#fff;padding:24px 16px;z-index:1000}.brand{display:flex;align-items:center;gap:12px;padding:0 10px 30px}.brand-icon{width:44px;height:44px;border-radius:13px;background:linear-gradient(135deg,var(--primary),#7c3aed);display:grid;place-items:center;font-size:21px;box-shadow:0 8px 20px #2563eb44}.brand b{font-size:15px;display:block}.brand small{color:#9ca3af;font-size:10px}.menu-title{font-size:10px;letter-spacing:1.5px;color:#6b7280;font-weight:700;padding:12px 12px 7px}.nav-link{color:#aeb7c8!important;padding:11px 13px;border-radius:11px;margin:4px 0;display:flex;align-items:center;gap:12px;font-size:12px}.nav-link i{font-size:17px;width:21px}.nav-link:hover{background:#1f2937;color:#fff!important}.nav-link.active{background:linear-gradient(90deg,var(--primary),var(--indigo));color:#fff!important;box-shadow:0 8px 18px #2563eb33}.logout{position:absolute;bottom:18px;left:16px;right:16px}.main{margin-left:250px;min-height:100vh}.topbar{height:76px;background:#fff;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 34px;position:sticky;top:0;z-index:900}.crumb{font-size:11px;color:var(--muted)}.page-title{font-size:20px;font-weight:700;margin-top:2px}.profile{display:flex;align-items:center;gap:10px}.avatar{width:40px;height:40px;border-radius:50%;background:linear-gradient(135deg,var(--primary),#7c3aed);color:#fff;display:grid;place-items:center;font-weight:700}.content{padding:28px 34px 40px}.cardx{background:#fff;border:1px solid var(--line);border-radius:17px;box-shadow:0 7px 22px #1e293b09}.card-head{padding:17px 19px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between}.card-head h5{font-size:14px;font-weight:700;margin:0}.card-head small{font-size:10px;color:var(--muted)}.form-control,.form-select{border-color:#e1e6ef;border-radius:10px;font-size:12px;padding:10px 12px}.form-control:focus,.form-select:focus{border-color:#93c5fd;box-shadow:0 0 0 .2rem #2563eb12}.btn{border-radius:10px;font-size:12px;font-weight:600;padding:9px 13px}.btn-primary{background:linear-gradient(90deg,var(--primary),var(--indigo));border:0}.table{font-size:12px}.table th{font-size:10px;color:#8a95a8;border:0;padding:13px 9px}.table td{padding:13px 9px;border-color:#f0f2f6;vertical-align:middle}.badge-soft{background:#eff6ff;color:#2563eb;border-radius:8px;padding:6px 9px;font-size:10px;font-weight:600}.empty{padding:35px;text-align:center;color:var(--muted)}.product{cursor:pointer;transition:.2s}.product:hover{transform:translateY(-3px);box-shadow:0 12px 25px #1e293b15}.price{color:var(--primary);font-weight:700}.section-title{font-weight:700;font-size:16px}.sub{font-size:11px;color:var(--muted)}
@media(max-width:900px){.sidebar{width:72px;padding:20px 10px}.brand{padding:0 4px 28px}.brand>div:last-child,.nav-link span,.menu-title,.logout span{display:none}.nav-link{justify-content:center}.logout{left:10px;right:10px}.main{margin-left:72px}.topbar{padding:0 20px}.content{padding:22px 20px}}@media(max-width:600px){.topbar{height:auto;padding:14px 16px}.content{padding:17px 14px}.page-title{font-size:17px}.profile .user-text{display:none}}
</style></head><body>
<aside class="sidebar"><div class="brand"><div class="brand-icon"><i class="bi bi-shop"></i></div><div><b>RestoPOS</b><small>Point of Sale</small></div></div>
<div class="menu-title">MENU UTAMA</div>
<a class="nav-link <?=navActive('index.php')?>" href="index.php"><i class="bi bi-grid-1x2-fill"></i><span>Dashboard</span></a>
<?php if(in_array($role,['admin','kasir'])): ?><a class="nav-link <?=navActive('pos.php')?>" href="pos.php"><i class="bi bi-cart3"></i><span>Kasir / POS</span></a><a class="nav-link <?=navActive('transactions.php')?>" href="transactions.php"><i class="bi bi-receipt"></i><span>Transaksi</span></a><?php endif; ?>
<?php if($role==='admin'): ?><div class="menu-title">MASTER DATA</div><a class="nav-link <?=navActive('menus.php')?>" href="menus.php"><i class="bi bi-egg-fried"></i><span>Data Menu</span></a><a class="nav-link <?=navActive('categories.php')?>" href="categories.php"><i class="bi bi-tags"></i><span>Kategori</span></a><?php endif; ?>
<?php if(in_array($role,['admin','manajer'])): ?><div class="menu-title">LAPORAN</div><a class="nav-link <?=navActive('reports.php')?>" href="reports.php"><i class="bi bi-bar-chart-line"></i><span>Laporan</span></a><?php endif; ?>
<a class="nav-link logout" href="logout.php"><i class="bi bi-box-arrow-left"></i><span>Keluar</span></a></aside>
<main class="main"><header class="topbar"><div><div class="crumb">RestoPOS / <?=htmlspecialchars(ucfirst(pathinfo($page,PATHINFO_FILENAME)))?></div><div class="page-title"><?=htmlspecialchars($page==='index.php'?'Dashboard':ucfirst(pathinfo($page,PATHINFO_FILENAME)))?></div></div><div class="profile"><div class="text-end user-text"><b style="font-size:12px"><?=htmlspecialchars($name)?></b><div style="font-size:10px;color:var(--muted)"><?=htmlspecialchars(ucfirst($role))?></div></div><div class="avatar"><?=strtoupper(substr($name,0,1))?></div></div></header><section class="content">