<?php require 'config.php'; auth();
$totalHariIni=$conn->query("SELECT COALESCE(SUM(total_amount),0) v FROM transactions WHERE status='paid' AND DATE(created_at)=CURDATE()")->fetch_assoc()['v'];
$trxHariIni=$conn->query("SELECT COUNT(*) v FROM transactions WHERE status='paid' AND DATE(created_at)=CURDATE()")->fetch_assoc()['v'];
$stokMenipis=$conn->query("SELECT COUNT(*) v FROM menus WHERE stock<=5")->fetch_assoc()['v'];$totalMenu=$conn->query("SELECT COUNT(*) v FROM menus")->fetch_assoc()['v'];
$totalKategori=$conn->query("SELECT COUNT(*) v FROM categories")->fetch_assoc()['v'];$totalTransaksi=$conn->query("SELECT COUNT(*) v FROM transactions WHERE status='paid'")->fetch_assoc()['v'];
$totalPendapatan=$conn->query("SELECT COALESCE(SUM(total_amount),0) v FROM transactions WHERE status='paid'")->fetch_assoc()['v'];$labels=[];$values=[];
for($i=6;$i>=0;$i--){$d=date('Y-m-d',strtotime("-$i days"));$labels[]=date('d M',strtotime($d));$q=$conn->query("SELECT COALESCE(SUM(total_amount),0) v FROM transactions WHERE status='paid' AND DATE(created_at)='$d'")->fetch_assoc()['v'];$values[]=(int)$q;}
$recent=$conn->query("SELECT t.*,u.name cashier FROM transactions t JOIN users u ON u.id=t.user_id WHERE t.status='paid' ORDER BY t.created_at DESC LIMIT 6");include 'partials/header.php';?>
<div class="cardx p-4 mb-4" style="background:linear-gradient(120deg,#1d4ed8,#4f46e5);color:white;position:relative;overflow:hidden"><div style="position:relative;z-index:2"><div style="font-size:23px;font-weight:700">Selamat datang, <?=htmlspecialchars($_SESSION['user']['name'])?>! 👋</div><div style="color:#dbeafe;font-size:12px;margin-top:5px">Pantau penjualan, stok, dan aktivitas restoran dari satu dashboard.</div><a href="pos.php" class="btn btn-light mt-3"><i class="bi bi-plus-lg me-1"></i> Buat Transaksi</a></div></div>
<div class="row g-3 mb-4">
<?php foreach([['Pendapatan Hari Ini',rupiah($totalHariIni),'bi-cash-stack','blue'],['Transaksi Hari Ini',$trxHariIni,'bi-receipt-cutoff','green'],['Stok Menipis',$stokMenipis,'bi-box-seam','orange'],['Total Menu',$totalMenu,'bi-egg-fried','purple']] as $s): ?><div class="col-6 col-xl-3"><div class="cardx p-3 h-100"><div class="d-flex justify-content-between"><div class="stat-icon <?=$s[3]??'blue'?>" style="width:43px;height:43px;border-radius:12px;background:#eff6ff;color:#2563eb;display:grid;place-items:center;font-size:19px"><i class="bi <?=$s[2]?>"></i></div></div><div class="sub mt-3"><?=$s[0]?></div><div style="font-size:20px;font-weight:700;margin-top:3px"><?=$s[1]?></div></div></div><?php endforeach; ?></div>
<div class="row g-3"><div class="col-xl-8"><div class="cardx"><div class="card-head"><div><h5>Grafik Pendapatan</h5><small>7 hari terakhir</small></div><a href="reports.php" class="btn btn-sm btn-outline-primary">Lihat Laporan</a></div><div style="height:315px;padding:18px 20px"><canvas id="salesChart"></canvas></div></div></div>
<div class="col-xl-4"><div class="cardx h-100"><div class="card-head"><div><h5>Ringkasan Data</h5><small>Informasi sistem</small></div></div><div class="p-3"><div class="py-3 border-bottom"><b><?=$totalKategori?> Kategori</b><div class="sub">Kategori menu tersedia</div></div><div class="py-3 border-bottom"><b><?=$totalTransaksi?> Transaksi</b><div class="sub">Transaksi sudah dibayar</div></div><div class="py-3"><b><?=rupiah($totalPendapatan)?></b><div class="sub">Total pendapatan</div></div></div></div></div></div>
<div class="cardx mt-3"><div class="card-head"><div><h5>Transaksi Terbaru</h5><small>Aktivitas pembayaran terakhir</small></div><a href="transactions.php" class="btn btn-sm btn-light">Semua Transaksi <i class="bi bi-arrow-right"></i></a></div><div class="table-responsive p-2"><table class="table mb-0"><thead><tr><th>INVOICE</th><th>KASIR</th><th>METODE</th><th>WAKTU</th><th class="text-end">TOTAL</th><th></th></tr></thead><tbody><?php if($recent&&$recent->num_rows): while($t=$recent->fetch_assoc()):?><tr><td><b><?=$t['invoice_code']?></b></td><td><?=$t['cashier']?></td><td><span class="badge-soft"><?=htmlspecialchars(strtoupper($t['payment_method']))?></span></td><td><?=date('d/m/Y H:i',strtotime($t['created_at']))?></td><td class="text-end"><b><?=rupiah($t['total_amount'])?></b></td><td class="text-end"><a class="btn btn-sm btn-light" href="receipt.php?id=<?=$t['id']?>"><i class="bi bi-eye"></i></a></td></tr><?php endwhile; else:?><tr><td colspan="6" class="empty">Belum ada transaksi.</td></tr><?php endif;?></tbody></table></div></div>
<script>new Chart(document.getElementById('salesChart'),{type:'line',data:{labels:<?=json_encode($labels)?>,datasets:[{data:<?=json_encode($values)?>,borderWidth:3,tension:.4,fill:true,backgroundColor:'rgba(37,99,235,.08)',borderColor:'#2563eb',pointRadius:4}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>' Rp '+new Intl.NumberFormat('id-ID').format(c.raw)}}},scales:{y:{beginAtZero:true,ticks:{font:{size:10},callback:v=>'Rp '+new Intl.NumberFormat('id-ID',{notation:'compact'}).format(v)}},x:{grid:{display:false},ticks:{font:{size:10}}}}}});</script><?php include 'partials/footer.php';?>